name = "abr-geocoder-workers"
main = "src/interface/hono-server/index.ts"
compatibility_date = "2024-09-08"
compatibility_flags = [ "nodejs_compat" ]
minify = true


[[d1_databases]]
binding = "DB"
database_name = "abr-geocoder"
database_id = "2f24283c-352c-488f-af77-4bfcc07a0775"
preview_database_id = "local-test-db"
